language: generic 
services:
    - docker
before_install:
    - docker build -t ccollot/terraformfib -f ./Dockerfile .
    - docker run -it --entrypoint '/bin/sh' -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e TF_VAR_POSTGRES_USERNAME -e TF_VAR_POSTGRES_PASSWORD ccollot/terraformfib build.sh

script:
   - docker run -it --entrypoint '/bin/sh' -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e TF_VAR_POSTGRES_USERNAME -e TF_VAR_POSTGRES_PASSWORD ccollot/terraformfib deploy.sh
